### ISSUE TITLE
Use Next.JS template to allow disabling sidebar per-page

### ISSUE THREAD

**Issue by lacymorrow** [fuma-nama/fumadocs#1188]
### What problem will this feature address?

https://nextjs.org/docs/app/api-reference/file-conventions/template

### Describe the solution you'd like

The docs state:

>[Disable Sidebar from Pages](https://fumadocs.vercel.app/docs/ui/layouts/docs#disable-sidebar-from-pages)
>This is not supported. Due to the limitations of App Router, layouts are not re-rendered when navigating between pages. It is an anti-pattern to change your layout from a page.

>You can consider:

>Disable sidebar from the entire layout.
>Create a [MDX Page](https://fumadocs.vercel.app/docs/ui/layouts/page#mdx-page) in a layout that doesn't contain a sidebar.
>https://fumadocs.vercel.app/docs/ui/layouts/docs#disable-sidebar-from-pages

This should be possible with the app router now

### Describe alternatives you've considered

You should be able to use `template.js` (vs `layout.js`) to accomplish this, as they are re-rendered every time.

### Additional context

https://nextjs.org/docs/app/api-reference/file-conventions/template

**Comment by fuma-nama** [comment]
This is not true, resetting the state of docs layout causes the current opening folders/states to lose. The reason why it's not a good idea to use layout is that it requires rendering per-page which against the need of layout, it's better to have multiple layout for most use cases, since have no sidebar won't be a better UX.
