### ISSUE TITLE
feat: remote OpenAPI spec

### ISSUE THREAD

**Issue by juliusmarminge** [fuma-nama/fumadocs#232]
**Is your feature request related to a problem? Please describe.**

I'd like to load an OpenAPI schema from a URL, e.g. `https://uploadthing.com/openapi.json`

**Describe the solution you'd like**

Preferably the schema would be parsed on every request (with possibility to cache the page using next.js cache primitives), or that the CLI would fetch the schema and generate it on build

**Describe alternatives you've considered**

-

**Comment by fuma-nama** [comment]
It is already possible by fetching the schema in every build with a custom script. You can use the docs generator from [Fumadocs OpenAPI](https://fumadocs.vercel.app/docs/ui/openapi#usage), or import the package in the script for advanced usages.

**Comment by juliusmarminge** [comment]
alright that answered half the question, what if i wanna fetch it on every request to the openapi docs page?

**Comment by fuma-nama** [comment]
It's not theoretically possible because once Fumadocs MDX compiles your MDX files, they can't be modified at runtime (in production build). Fumadocs OpenAPI generates file content rather than component, therefore you will need a on-demand MDX renderer like next-mdx-remote.

**Comment by fuma-nama** [comment]
To fetch it in every request, you can fetch the schema, generate MDX file content with Fumadocs OpenAPI, and finally render it with `next-mdx-remote`.

**Comment by songkeys** [comment]
It seems that fumadocs does not offer built-in support for generating OpenAPI on every request. I find this sentence in the [docs](https://fumadocs.vercel.app/docs/ui/openapi/configurations) a bit confusing in this case:

> On Next.js server, the schema is dynamically fetched when the APIPage component renders.

<img width="850" alt="SCR-20241002-qkld" src="https://github.com/user-attachments/assets/c3b54875-b4a4-4e5d-8b80-9f727a3474e5">

It gives the impression that the schema is fetched dynamically with each request. However, theoretically, that’s not the case since `generateFiles` is executed when we run the script manually. I believe this needs to be clarified more clearly.

**Comment by fuma-nama** [comment]
This discussion happened before the release of Fumadocs OpenAPI v5. Now it's possible with `APIPage` component and Next.js ISR or `revalidate` config.

**Comment by songkeys** [comment]
@fuma-nama Ah I see! I missed the `APIPage` component. If I understand correctly, we can do this directly without using `generateFiles`?

```mdx
---
title: Demo Museum API
description: A demo documentation for the OpenAPI generator
index: true
---

<APIPage
  document="https://remote-api.com/museum.json"
  hasHead={false}
/>
```

Haven't tried this yet. But as I said, the `generateFiles` doc says something about dynamic rendering but i don't see we can actually use that `generateFiles` funciton to dynamic render because it writes files to the disk? Or we should put that function in the corresponding server component?

I can't see any clue in the doc. If you could clarify a bit more or provide a demo, that'd be really helpful. Thank you for your work!

**Comment by fuma-nama** [comment]
No, everything is now rendered with the API page component, which you can use without an actual MDX file. What that function does is create a MDX file as it is required to build sites/page tree statically. If it's meant to be dynamic, you shouldn't use it.
