### ISSUE TITLE
Disable TailwindCSS preflight

### ISSUE THREAD

**Issue by nihgwu** [fuma-nama/fumadocs#238]
First of all, this is a great project, I've been watch it's growth for a while, I really love the evolution, nice job 👍 

I'm considering moving a Design System website from Nextra to fumadocs, and because you both are using TailwindCSS as styling solution, so we are facing the same problem I initially raised [here](https://github.com/shuding/nextra/issues/1403), it's a big problem for us

**Describe the solution you'd like**

At least we can disable preflight and fix the styles where needed so it doesn't pollute the user space, I guess it should just a normal reset and patch styles for buttons

Ideally I'd love to see classNames been compiled, then you don't need to prefix the classNames as Nextra does, I wanted to build my own documentation long ago, until I see this project, I love the design a lot, if we can address my concern, then it's just my dream comes true

If it was me, probably I would just choose CSS Modules, so style is isolated by nature, but as now it's started with TailwindCSS, an easier path is using UnoCSS and it's [compile class](https://unocss.dev/transformers/compile-class) feature, so basically the change will be prefixing classNames with `:uno:` or `:fuma:`, then that's it

**Comment by fuma-nama** [comment]
Migrating to UnoCSS is nearly impossible, it at least requires a big refactor to the codebase and many projects using the DocsUI Tailwind CSS plugin will be broken, with no workarounds. It is no longer plausible.

Fumadocs UI will remain opinionated on UI and strongly rely on Tailwind CSS. In my opinion, fencing your design system showcases/components in an `iframe` element would be more reasonable. It creates an isolated environment so regardless of what, including your global styles injected from docs, will not affect your components in the frame.

For the suboptimal solution, you can remove the `@layer base` from your stylesheet file (only available for Tailwind CSS integration). Since Tailwind CSS injects preflight into the base layer, this can prevent preflight. You can refer to their docs for more info.

**Comment by nihgwu** [comment]
> and many projects using the DocsUI Tailwind CSS plugin will be broken, with no workarounds

we can still use UnoCSS internally and keep the TailwindCSS to user space

> For the suboptimal solution, you can remove the `@layer base` from your stylesheet file

why not just [disable preflight](https://tailwindcss.com/docs/preflight#disabling-preflight), it's just some global reset and can be fixed at component level

**Comment by fuma-nama** [comment]
> why not just [disable preflight](https://tailwindcss.com/docs/preflight#disabling-preflight), it's just some global reset and can be fixed at component level

The base layer also includes other global resets, like the default border color. Solely disabling the core plugin doesn't remove it.

**Comment by nihgwu** [comment]
> Honestly, I am not in favor of making a big refactor just for migrating to UnoCSS.

I'm not saying we have to use UnoCSS, I just think that's the cheapest way to achieve className encapsulation, we don't have to do it

> Having a consistent look across browsers is the entire point of Preflight

I would say `normalize.css` is fine, but `preflight` is too much, it changes a button's appearance to a plain text

> I'm not seeing any points that can persuade me to put efforts into migration

I would say if disabling `preflight` is not a migration, just to not pollute user space styling

**Comment by fuma-nama** [comment]
> I would say normalize.css is fine, but preflight is too much, it changes a button's appearance to a plain text

I believe you can fix this in component level. If you think normalising button is inappropriate, you should instead open an issue in tailwind css’s repo.
