### ISSUE TITLE
Rewrite the docs

### ISSUE THREAD

**Issue by fuma-nama** [fuma-nama/fumadocs#374]
### What problem will this feature address?

Few years ago, I built fumadocs.
At the time, I wasn't experienced in authoring docs, especially in making tutorial content. This makes the docs of fumadocs became messy and unfriendy for beginners.
I think we really need a rewrite of docs.

### Describe the solution you'd like

Make all shared pages (e.g. page conventions) to be accessible from all sidebars, and rewrite most of the content.

### Describe alternatives you've considered

N/A

**Comment by fuma-nama** [comment]
I have improve some sections of the docs, welcome for feedback!

**Comment by seangray-dev** [comment]
Hey @fuma-nama, currently I'm trying to figure out how to change the order of the side-bar navigation, I couldn't find anything in the docs for this. 

For example I would like this to be the order: 

- Getting Started
- Dashboard 

But currently its being rendered as this by default: 
- Dashboard
- Getting Started

Thanks for your help!

**Comment by fuma-nama** [comment]
You are looking for this: https://fumadocs-dev.vercel.app/docs/headless/page-conventions#meta

**Comment by ederross** [comment]
heey, so... I am seeing the docs and still not figuring out how to use the componets yet haha I am missing something but I can't find it. 

When I try to add a component to the mdx file, the erro below appears:

<img width="1156" alt="Screenshot 2024-05-21 at 12 15 56" src="https://github.com/fuma-nama/fumadocs/assets/35125885/57348abe-fdf0-478f-87b6-1b710902be3c">

Can anyone help me?

**Comment by fuma-nama** [comment]
Read the error message, it tells you your `hello.mdx` is missing a title in frontmatter.

**Comment by fuma-nama** [comment]
Also this is not a thread to fix issues, please open a Q&A question in discussion or fire an issue next time.

**Comment by ederross** [comment]
> Also this is not a thread to fix issues, please open a Q&A question in discussion or fire an issue next time.

thanks!! You are awesome!!! I'm love with fumadocs

**Comment by ZoroZh** [comment]
Hi @fuma-nama ,thank you for your great job. I'm trying to use fumadocs-twoslash. i followed UI-doc .but i just render a raw code block.
![WeChatad6e9b6820cc1030bf9961758f0110f8](https://github.com/fuma-nama/fumadocs/a
![WeChat148e5874ccde5715b6a0bc3b84ae58e1](https://github.com/fuma-nama/fumadocs/assets/3
![WeChat8e0c367040dbedfc2cd1e6b44ab9ed51](https://github.com/fuma-nama/fumadocs/assets/38368479/9655ebad-cbfd-4260-868c-9533950b2426)
8368479/e12a97c7-2e86-45d7-ac9d-6cf23e6d2d9f)
ssets/38368479/31a19af2-aafb-
![WeChat936f8db7312340ebb9bb739fcc3c1418](https://github.com/fuma-nama/fumadocs/assets/38368479/e97a7618-f448-40e2-9da5-406d68ddda51)
4e38-83f1-2ec79e83545f)
can you help me out

**Comment by fuma-nama** [comment]
Can you open a separate issue instead? This issue is only for suggesting docs changes.

**Comment by changeelog** [comment]
Hey, fuma-nama!

Currently, the Markdown page in the [Fumadocs website](https://fumadocs.vercel.app/docs/headless/mdx) provides a number of useful plugins for documentation. 

My proposal is to rewrite the Markdown page to include the following:

- A list of the rehype and remark plugins that are currently used in Fumadocs, along with a concise explanation of what each plugin does. I like how similar thing is implemented on [VitePress's website](https://vitepress.dev/guide/markdown)

- A section on how to install and configure custom rehype and remark plugins. It's already done admirably. But I just couldn't not include it here, because otherwise the “puzzle” wouldn't be complete

- A guide on creating custom rehype and remark plugins from scratch. [Docusaurus](https://docusaurus.io/docs/markdown-features/plugins#creating-new-rehyperemark-plugins) have some information about this on their website.

In addition to this, a [Get Started page](https://fumadocs.vercel.app/docs/mdx) could also be slightly re-newed. I like the way it looks now, but at the beginning I'd like to add a section about prerequisites (node version x or higher, etc). It is also worth mentioning the questions that will be asked during installation.

**Comment by fuma-nama** [comment]
> A guide on creating custom rehype and remark plugins from scratch
The other suggestions are great, but maybe this can stay outside of fumadocs docs, remark/rehype has their own guide in writing plugins.

**Comment by fuma-nama** [comment]
> It is also worth mentioning the questions that will be asked during installation.

Could you name a few examples? We currently have mentioned some terminologies which are useful for beginners, but except from the FAQ section, I don't have idea about how a real beginner think about it, and what questions they may ask.

There is indeed a prerequisite of Node.js version (18+) which is added to `package.json`, it will be warned by package managers. I'll add this to the guide.

**Comment by changeelog** [comment]
> Could you name a few examples?

Oh, sure! Take a look at those screenshots. They are clickable and lead to the source site. Such an implementation would allow us to talk a little deeper about the installation process without describing it in too much depth.

![nextjs](https://nextjs.org/docs/app/api-reference/create-next-app)

![vitepress](https://vitepress.dev/guide/getting-started)

**Comment by fuma-nama** [comment]
I would just write it as text tho, but it's indeed a good suggestion.

**Comment by fuma-nama** [comment]
I'm working on the docs, feel free to check the preview here: https://fumadocs-dev.vercel.app/docs/ui/components/type-table

**Comment by fuma-nama** [comment]
I've added a section for writing documents, for beginners who may not know much about programming.
Feel free to leave some feedback here

**Comment by fuma-nama** [comment]
Consider adding icons in the same style for other subsections. Currently only UI has its own icons.

![core](https://github.com/fuma-nama/fumadocs/assets/135520429/814e35f9-b23d-44a2-81aa-31af86294565)
![mdx](https://github.com/fuma-nama/fumadocs/assets/135520429/efac58ab-6963-474f-8afe-c2d62a26d1c9)
![ui](https://github.com/fuma-nama/fumadocs/assets/135520429/b245de0d-f741-4abc-a3a1-ef787296504c)

For icons sources we could look up here
[https://github.com/iconify/iconify](https://github.com/iconify/iconify)

Speaking of MDX section, I like those icons:
- Getting Started - maybe the same icon from UI section
- Image Optimization - [https://icon-sets.iconify.design/carbon/image/](https://icon-sets.iconify.design/carbon/image/)
- Last Modified Time - [https://icon-sets.iconify.design/carbon/time/](https://icon-sets.iconify.design/carbon/time/)
- Generate Search Indexes - This one is kinda hard to choose. Maybe this one - [https://icon-sets.iconify.design/carbon/search-advanced/](https://icon-sets.iconify.design/carbon/search-advanced/)

Speaking of Core section, I like those icons:
- Quick Start - maybe the same icon from UI section? Also maybe the naming of this specific section should be consistent across the website? For now we have: 2x Quick Starts and Getting Started
- Page Conventions - [https://icon-sets.iconify.design/carbon/document/](https://icon-sets.iconify.design/carbon/document/)
- Page Tree - I dont kinda like this one, but others seem to make no sense. [https://icon-sets.iconify.design/carbon/tree-view/](https://icon-sets.iconify.design/carbon/tree-view/)
- Internationalization - [https://icon-sets.iconify.design/carbon/flight-international/](https://icon-sets.iconify.design/carbon/flight-international/) or the same icon from UI section

I'll write about the navbar thingy later.

_Originally posted by @changeelog in https://github.com/fuma-nama/fumadocs/issues/430#issuecomment-2156445068_

**Comment by changeelog** [comment]
I'm free from traveling for now, so it's the right time to write all the things I wanted to write. I want to note that packages does not have a readme for the [MDX module](https://github.com/fuma-nama/fumadocs/tree/dev/packages/mdx), and the link in the readme for [core module](https://github.com/fuma-nama/fumadocs/blob/dev/packages/core/README.md) leads to the main site, and not to the site page dedicated to this (as in the case of the [UI module](https://github.com/fuma-nama/fumadocs/blob/dev/packages/ui/README.md)). Next, I will try to offer something in more detail for each of the modules.

**1. Core**

**1.1. Quick Start Page**

It would be appropriate to include something similar at the top of this page. Maybe rename this sections (on the screenshot) to something like `Overwiew` and put the text under the screenshot right there

![image](https://github.com/fuma-nama/fumadocs/assets/135520429/07038ae0-37be-452e-877d-bf9b341ff1c2)

This guide provides a detailed explanation of how to set up a basic documentation website using Fumadocs Core. It will cover the following topics:

**Project Setup:** Initiating a new project and installing Fumadocs Core.

**Choosing a Content Source:** Integrating your documentation content using Fumadocs MDX, Contentlayer or custom sources.

**Building the Page Tree:** Structuring your documentation for navigation.

**Creating Your First MDX Page:** Writing content and using Fumadocs components.

**Exploring Core Features:** A glimpse into search, breadcrumbs, and more.

---

Further in the text, it seems necessary to delve more into the "formalities" of the installation process. Either clarify the creation of a new directory for the project and go through the installation process in detail, or clarify that the user should select the directory where the project should be installed (`cd` command / after the suggestions there're screens from nextjs website displaying "ways" of describing this thing because this is kinda polluted).

**1. Project Setup**

**1.1. Create a new project**

```
mkdir my-fumadocs-project
cd my-fumadocs-project
```

**1.2. Initialize your project**

Using **npm**:

```
npm init -y
```

Using **yarn**:

```
yarn init -y
```

Using **pnpm**:

```
pnpm init
```

Using **bun**:

```
bun init
```

**1.3 Install Fumadocs Core:**

```
npm install fumadocs-core
# or
pnpm add fumadocs-core
# or
yarn add fumadocs-core
# or
bun add fumadocs-core
```

You will then be asked the following prompts:

```
> npx
> create-fumadocs-app

┌  Create Fumadocs App
│
◆  Project name
│  my-app      
|
◆  Choose a content source
│  ○ Fumadocs MDX
│  ○ Contentlayer
│
◆  Use Tailwind CSS for styling?
│  ○ Yes / ○ No
│
◆  Do you want to install packages automatically? (detected as npm)
│  ○ Yes / ○ No
└
```

Once you've answered the prompts, a new project will be created with the correct configuration depending on your answers.


![image](https://github.com/fuma-nama/fumadocs/assets/135520429/bd479ea1-f949-4a07-8e44-f65e1d545332)

Source: [https://nextjs.org/docs/app/api-reference/create-next-app](https://nextjs.org/docs/app/api-reference/create-next-app)

![image](https://github.com/fuma-nama/fumadocs/assets/135520429/61cddc2d-d215-4353-8b24-113d950111f4)

Source: [https://nextjs.org/learn-pages-router/basics/create-nextjs-app/setup](https://nextjs.org/learn-pages-router/basics/create-nextjs-app/setup)

---

Let's move on to selecting a content source and maybe change the existing thing (on the screenshot) to this (what comes after the screenshot)

![source](https://github.com/fuma-nama/fumadocs/assets/135520429/491d5798-0893-4b84-9cfe-e93d893ab106)

Fumadocs Core is content-agnostic. You have the flexibility to use:

**Fumadocs MDX (Recommended):** Seamless integration with Fumadocs UI and core features.

**Contentlayer:** Powerful data validation and transformation of your content into type-safe JSON data.

**Custom Sources:** Adapt any data source to fit your needs.

---

I like the continuation of this page.

![image](https://github.com/fuma-nama/fumadocs/assets/135520429/9d01277f-e9e0-4568-acb8-32dad77f6af5)


However I'd change `Enjoy` heading to something like `Exploring Core Features` and leave the cards as they are now!

**Comment by changeelog** [comment]
**1.2. Page Conventions**

Change the tagline from "Organize documents with file-system based routing" to " Structuring Your Documentation with Fumadocs".

![image](https://github.com/fuma-nama/fumadocs/assets/135520429/8ed57a4f-017c-4ca0-b830-d22002ec7dd1)


Add a paragraph here of something like this:

Fumadocs leverages a file-system based routing approach to organize your documentation. This convention, shared by content sources like Fumadocs MDX, provides a clear and intuitive structure for managing your pages.

Next, I would like to get rid of longreadness-feeling a little bit, because from the excessive number of headers, webpage seems to be quite large (even tho it isn't).

![image](https://github.com/fuma-nama/fumadocs/assets/135520429/2c55e5c2-49db-425c-b3d6-6b348c18ed76)

**Comment by changeelog** [comment]
**1.3. Page Tree**

The page tree defines the hierarchical structure of your documentation site. It encompasses all pages, folders, and separators, providing the blueprint for navigation elements like the sidebar and breadcrumbs.

Important: The page tree is sent to the client. Avoid storing sensitive or large data within it. Unserializable data, such as functions, cannot be included.

## Node Types

The page is composed of three node types:

**1. Page**

Represents a single page in your documentation.

| Property | Type | Default| Description |
|--------- | ---------- | ------- | ------- |
| `type` | `"page"` | - | Identifies the node as a page. |
| `name` | `string` | - | The display name of the page. |
| `url` | `string` | - | The URL path to the page. |
| `external` | `boolean` | - | Indicates if the URL is external (optional). |
| `icon` | `ReactElement<any, string \| JSXElementConstructor<any>>` | - | A React element representing the page's icon (optional). |

**Comment by changeelog** [comment]
**1.4. Internationalization**

Change this paragraph (highlighted on the screen) to something like this (the text under the screenshot)

![image](https://github.com/fuma-nama/fumadocs/assets/135520429/337c68a6-1354-4091-9270-aea3ee491be1)

Expand the reach of your documentation by seamlessly integrating multi-lingual support with FumaDocs. This guide will walk you through the process of empowering a global audience to access your content in their preferred language.

**Comment by changeelog** [comment]
1.5 Breadcrumbs

Is being written

**Comment by changeelog** [comment]
1.6 Link

Is being written

**Comment by changeelog** [comment]
1.7 Sidebar

Is being written

**Comment by changeelog** [comment]
1.8 TOC

Is being written

**Comment by changeelog** [comment]
1.9 Find Neighbours 

Reserved

**Comment by changeelog** [comment]
1.10 Get TOC

The `getTableOfContents` function is a utility that parses the table of contents (TOC) from a Markdown or MDX content. It uses the `remark` library and the `remark-heading` plugin to extract the headings from the content and generate a structured table of contents.

## Usage

To parse the table of contents from a Markdown or MDX content, follow these steps:

1. Import the `getTableOfContents` function from `fumadocs-core/server`:

```
import { getTableOfContents } from 'fumadocs-core/server';
```

2. Call the `getTableOfContents` function with the Markdown or MDX content as a string:

```
const toc = await getTableOfContents(content);
```

The `getTableOfContents` function returns a promise that resolves to an array of `TOCItemType` objects representing the table of contents.

Note: If you're using a Content Management System (CMS), it's recommended to use the API provided by the CMS to retrieve the table of contents instead of parsing it manually.

### Output

The `getTableOfContents` function returns an array of `TOCItemType` objects. Each `TOCItemType` object represents a heading in the table of contents and has the following properties:

`title` (string): The text content of the heading.
`url` (string): The URL fragment that points to the heading in the document.
`depth` (number): The nesting level of the heading (e.g., 1 for top-level headings, 2 for subheadings, etc.).

**Comment by changeelog** [comment]
1.11 Last Modified Time

The getGithubLastEdit function is a utility that retrieves the last edit time of a file in a GitHub repository. It uses the GitHub API to fetch the commit information for the specified file and returns the timestamp of the last modification.

## Usage

To get the last edit time of a file in a GitHub repository follow these steps:

1. Import the `getGithubLastEdit` function from `fumadocs-core/server`:

```
import { getGithubLastEdit } from 'fumadocs-core/server';
```
2. Call the `getGithubLastEdit` function with the requited options:

```
const lastEditTime = await getGithubLastEdit({
  owner: 'your-username',
  repo: 'your-repository',
  path: 'path/to/file.md',
});
```

The `getGithubLastEdit` function returns a promise that resolves to a `Date` object representing the last edit time of the file. If the file is not found or has no commit history, the function returns `null`.

Options

The `getGithubLastEdit` function accepts an object with the following options:

`owner` (string, required): The owner of the GitHub repository.
`repo` (string, required): The name of the GitHub repository.
`path` (string, required): The path to the file within the repository.
`token` (string, optional): The GitHub access token for authentication. If provided, it allows for a higher rate limit.
`params` (object, optional): Additional query parameters to include in the API request.
`options` (object, optional): Custom options to pass to the fetch function.

## GitHub Token

When making requests to the GitHub API, you may encounter rate limits, especially in development mode. To avoid hitting the rate limit, you can provide a GitHub access token using the `token` option. This allows for a higher rate limit.

Learn more about [Authenticating to the REST API](https://docs.github.com/en/rest/overview/authenticating-to-the-rest-api).

```
import { getGithubLastEdit } from 'fumadocs-core/server';

const lastEditTime = await getGithubLastEdit({
  owner: 'your-username',
  repo: 'your-repository',
  path: 'path/to/file.md',
  token: `Bearer ${process.env.GITHUB_TOKEN}`,
});
```

**Note**: If you don't need the last edit time functionality in development mode, you can skip calling the `getGithubLastEdit` function to avoid potential rate limit issues.

```
const lastEditTime =
  process.env.NODE_ENV === 'development'
    ? null
    : await getGithubLastEdit({
        owner: 'your-username',
        repo: 'your-repository',
        path: 'path/to/file.md',
      });
```

**Comment by fuma-nama** [comment]
This is really too long for this thread, perhaps you can open a PR instead?

**Comment by changeelog** [comment]
> This is really too long for this thread, could you open a PR instead? Thanks!

Oh, definitely!
