### ISSUE TITLE
GitHub action to generate from OpenAPI and deploy to GitHub pages

### ISSUE THREAD

**Issue by zefir-git** [fuma-nama/fumadocs#614]
### What problem will this feature address?

As per the [Fumadocs OpenAPI docs](https://fumadocs.vercel.app/docs/ui/openapi), I need to create several files and configs to generate OpenAPI docs.

### Describe the solution you'd like

It would be much simpler if I could just add an action to my GitHub repository that will generate and deploy to GitHub pages whenever the `openapi.yaml` is updated on the main branch, without requiring any additional Fumadocs files to be created in the repository (except for the action yaml)

### Describe alternatives you've considered

-

**Comment by fuma-nama** [comment]
You can always write a script that generates document based on your OpenAPI schema and use a command to run the script in your GitHub action:

```bash
node ./scripts/gen-docs.mjs
```

**Comment by zefir-git** [comment]
I know I can do that. The aim of this feature request was to simplify deployment to GH pages (or another deployment environment) by moving all configurations to a single Action. This would eliminate the need to set up another Node.js project inside your existing Node.js project or install dev dependencies that will only be used in a deployment Action.

**Comment by fuma-nama** [comment]
I think adding a dependency to the project and write a script isn't a problem. It also keeps the max flexibility since you cannot pass functions to configurations of an action. Most importantly, you still need to install Node.js and Fumadocs OpenAPI to generate documents, because the package itself is written in JavaScript.
I don't want to publish and maintain a GitHub Action while it doesn't have much benefits to users.
